name: Deploy App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/devops-project/app

            echo "Stopping all running containers..."
            docker stop $(docker ps -aq) || true

            echo "Removing all containers..."
            docker rm $(docker ps -aq) || true

            echo "Building Docker image..."
            docker build -t devops-app .

            echo "Running new container..."
            docker run -d -p 3000:3000 --name app devops-app
